<a href="https://colab.research.google.com/github/nguyentrongnguyen3004-eng/Th_Deep_Learning/blob/main/TH_DeepLearning_B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**3.1. Tạo array 1 chiều**

In [ ]:
import numpy as np

# Cách 1
# Tạo list
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)

my_numpy_arrat = np.array(my_list)
print('Numpy array: ', my_numpy_arrat)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [ ]:
# Cách 2
import numpy as np
a = np.array([1, 9 ,15, 39])
print(a)

[ 1  9 15 39]


**3.2. Array 2 chiều**

In [ ]:
import numpy as np

c = np.array([(1, 2, 3), (4, 5, 6)])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


**3.3. Array 3 chiều**

In [ ]:
import numpy as np

d = np.array([[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


**3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1**

In [ ]:
import numpy as np

e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**3.5. Reshape và Flatten ma trận**


**3.5.1. Reshape thay đổi kích thước ma trận**

In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)
f = e.reshape(3, 2)
print(f)
g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]])

print(g)
print(g.shape)
h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


**3.5.2. Platten là chuyển array nhiều chiều về 1 chiều**

In [ ]:
import numpy as np

e = np.array([[1., 2., 3.], [4., 5., 6.]])
f = e.flatten()
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],\
              [[7., 8., 9.], [10., 11., 12.]]])
j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


**3.6. Thêm dòng dữ liệu với hstack và vstask**

In [ ]:
import numpy as np

f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n', h_stack)

v_stack = np.vstack((f, g))
print('Vertical Append\n', v_stack)


Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


**3.7. Sinh mảng số ngẫu nhiên**

**3.7.1. Sinh mảng số nguyên ngẫu nhiên**

In [ ]:
import numpy as np

a = np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
print('\n')

b = np.random.randint(100, size=(3, 4))
print('Random 2-D array\n', b)
print('\n')

c = np.random.randint(100, size=(3, 4, 3))
print('Random 3-D array\n', c)

Random 1-D array
 [18  0 20 39 15]


Random 2-D array
 [[79 47 85 55]
 [57 39 26 37]
 [58 71 24 17]]


Random 3-D array
 [[[76 23  0]
  [95 27 93]
  [39 52 47]
  [85 39 12]]

 [[86 88 56]
  [93 64  0]
  [74 73 44]
  [60 56 74]]

 [[69 28 60]
  [20 78  0]
  [35 74  4]
  [28 85 44]]]


**3.7.2. Sinh mảng số thực trong khoảng [0, 1]**

In [ ]:
import numpy as np

a = np.random.rand(5)
print('Random 1-D array\n', a)
print('\n')

b = np.random.rand(3, 4)
print('Random 2-D array\n', b)
print('\n')

c = np.random.rand(3, 4, 3)
print('Random 3-D array\n', c)



Random 1-D array
 [0.47465681 0.09360304 0.7881061  0.98241126 0.03063564]


Random 2-D array
 [[0.48682064 0.09406385 0.99367408 0.80695412]
 [0.63133036 0.11990762 0.49948246 0.66452934]
 [0.90314673 0.33351465 0.04920516 0.83389948]]


Random 3-D array
 [[[0.88915155 0.94348733 0.10397244]
  [0.10253285 0.97582374 0.50182492]
  [0.71626248 0.10754067 0.80933023]
  [0.83900291 0.49700471 0.72576807]]

 [[0.87361527 0.80052588 0.01178254]
  [0.63018241 0.69497344 0.3147563 ]
  [0.18621739 0.64476913 0.9779388 ]
  [0.72282898 0.7612803  0.23150525]]

 [[0.71904507 0.01918865 0.12650383]
  [0.17594654 0.22027978 0.96486493]
  [0.36922372 0.75447682 0.96606611]
  [0.12429227 0.14539581 0.11269056]]]


**3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian**

In [ ]:
import numpy as np

a = np.random.normal(5, 0.5, 10)
print(a)

[5.8667176  4.77664662 5.34675796 5.65530228 5.18276524 4.79594136
 4.67169094 4.17067072 5.20472608 4.29546511]


**3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước**

In [ ]:
import numpy as np

# Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print('Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước:\n', a)
print('\n')

# Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print('Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước:\n', b)

Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước:
 4


Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước:
 [[18 10  8 16 18]
 [18  4 16  4 10]
 [ 4  6  8 18  6]]


**3.8. Thay đổi giá trị của ma trận**

In [ ]:
import numpy as np

# Tạo ma trận 5 x 5 với số 1
A = np.matrix(np.ones((5, 5)))
print('The matrix\n', A)
print('\n')

np.array(A)[2] = 2
print('Change values of third row with array\n', A)
print('\n')

np.asarray(A)[2] = 2
print('Change values of third row with asarray\n', A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**3.9. Sinh dãy số theo khoảng cho trước**

**3.9.1. Dùng hàm arange**

In [ ]:
import numpy as np

# Tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)
print('\n')

# Tạo 20 số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 1  3  5  7  9 11 13 15 17 19]


**3.9.2. Dùng hàm linspace**

In [ ]:
import numpy as np

a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


**3.10. Index và slice**

In [ ]:
import numpy as np

# Slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a, '\n')
print('First row: ', a[0], '\n')
print('Second row: ', a[1], '\n')

# Indexing
print('Second column: ', a[:,1], '\n')
print('First colnmn: ', a[:,0], '\n')
print('First two values of second row: ', a[1, :2])

[[1 2 3]
 [4 5 6]] 

First row:  [1 2 3] 

Second row:  [4 5 6] 

Second column:  [2 5] 

First colnmn:  [1 4] 

First two values of second row:  [4 5]


**PANDAS**


**6. TÌM HIỂU ĐỐI TƯỢNG SERIES**

In [ ]:
import pandas as pd

# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a, '\n')
print('First value: ', a[0], '\n')

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b, '\n')
print('First value: ', b['a'], '\n')
# Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar, '\n')

0    1.0
1    2.0
2    3.0
dtype: float64 

First value:  1.0 

a    1.0
b    2.0
c    3.0
dtype: float64 

First value:  1.0 

day1    420
day2    380
day3    390
dtype: int64 



**7. TẠO ĐỐI TƯỢNG DATAFRAME**

In [ ]:
import pandas as pd

#Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h, '\n')

#Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

DataFrame: 
    0  1
0  1  2
1  3  4 

Numpy array: 
 [[1 2]
 [3 4]]


**Tạo DataFrame mảng 2 chiều có tên cột**

In [ ]:
import pandas as pd

dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [68]:
# Tạo mảng 20 x 4
import numpy as np
import pandas as pd

r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns = ['so1', 'so2', 'so3', 'so4'])
print(df.head()) #in 5 dòng đầu tiên

        so1       so2       so3       so4
0  0.147117 -0.445141 -0.126876 -0.714849
1  0.173456 -1.093635 -0.691445  1.078242
2 -0.494120 -0.347920 -0.171317 -0.447687
3 -1.059937  0.068458 -0.078224  0.081161
4 -0.057688 -0.140589 -1.187947  0.052474
