<a href="https://colab.research.google.com/github/nguyentrongnguyen3004-eng/Th_Deep_Learning/blob/main/th_deeplearning_b2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**3.1. Tensor 0-chiều**

In [1]:
import tensorflow as tf
import numpy as np

# Tạo tensor 0-chiều (Scalar) mặc định là int32
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.2. Tensor 1-chiều**

In [2]:
import tensorflow as tf
import numpy as np

# Tạo tensor 1-chiều
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.3. Tensor 2-chiều (ma trận)**


In [3]:
import tensorflow as tf
import numpy as np

# Tạo tensor 2-chiều
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.4. Tensor n-chiều (nhiều trục)**

In [4]:
import tensorflow as tf
import numpy as np

# Tạo tensor n-chiều
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.5. Thuộc tính của tensor**

In [5]:
import tensorflow as tf
import numpy as np

# Tạo tensor n-chiều
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)

print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


**3.6. Tạo tensor tự động gán giá trị 0 ban đầu**

In [6]:
import tensorflow as tf
import numpy as np

t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


**3.7. Tạo tensor tự động gán giá trị 1 ban đầu**

In [7]:
import tensorflow as tf
import numpy as np

t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


**3.8. Tạo tensor tự động với giá trị bất kỳ**

In [9]:
import tensorflow as tf
import numpy as np

t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


**3.9. Tạo tensor 1-chiều với hàm linspace**

In [10]:
import tensorflow as tf
import numpy as np

lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


**3.10. Tạo tensor 1-chiều với hàm range**

In [12]:
import tensorflow as tf
import numpy as np

range_tensor1 = tf.range(3.0, 7.0, delta = 0.5)
print(range_tensor1)

range_tensor2 = tf.range(3.0, delta = 0.5)
print(range_tensor2)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


**3.11. Tạo tensor với giá trị ngẫu nhiên**

In [17]:
import tensorflow as tf
import numpy as np

# Hàm random.normal
range_tensor_n1 = tf.random.normal([5])
print(range_tensor_n1)
print("\n")
range_tensor_n2 = tf.random.normal([3, 3])
print(range_tensor_n2)
print("\n")

# Hàm random.truncated_normal
range_tensor_t1 = tf.random.truncated_normal([5])
print(range_tensor_t1)
print("\n")
range_tensor_t2 = tf.random.truncated_normal([3, 2])
print(range_tensor_t2)
print("\n")
range_tensor_t3 = tf.random.truncated_normal([3, 2, 2])
print(range_tensor_t3)
print("\n")

# Hàm random.uniform
range_tensor_u1 = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor_u1)
print("\n")
range_tensor_u2 = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor_u2)
print("\n")
range_tensor_u3 = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor_u3)
print("\n")

# Ngẫu nhiên kết hợp Shuffle xáo trộn
range_tensor_shuffle = tf.random.uniform([5], minval=10, maxval=20)
print("Gốc trước khi shuffle:", range_tensor_shuffle)
print("Sau khi shuffle:", tf.random.shuffle(range_tensor_shuffle))

tf.Tensor([ 0.34687647  1.1261046  -0.15452613 -0.623581    0.26764584], shape=(5,), dtype=float32)


tf.Tensor(
[[-1.0252979  -1.2696898   0.01547301]
 [ 1.8827355   0.6295514   0.95098686]
 [-0.6562238   0.94028145  0.7048137 ]], shape=(3, 3), dtype=float32)


tf.Tensor([-0.19683534  0.5275591  -1.214848    0.5976333  -0.7578208 ], shape=(5,), dtype=float32)


tf.Tensor(
[[-0.1258505  -1.0937433 ]
 [-0.41855773  1.1980511 ]
 [-0.15754181 -1.2092648 ]], shape=(3, 2), dtype=float32)


tf.Tensor(
[[[ 0.97375923 -0.6856656 ]
  [ 1.9765818  -0.28502798]]

 [[ 0.01415333  0.4162242 ]
  [-1.928093    1.5524323 ]]

 [[ 0.49493587 -0.23310217]
  [-0.00234946 -1.1202714 ]]], shape=(3, 2, 2), dtype=float32)


tf.Tensor([12.953327 12.057134 17.861912 10.088321 12.354398], shape=(5,), dtype=float32)


tf.Tensor(
[[18.833809 11.744705]
 [16.847942 15.683435]
 [15.991978 18.158646]], shape=(3, 2), dtype=float32)


tf.Tensor(
[[[12.716797 10.677578 18.15875  16.701283 18.921906]
  [12.383936 14.3406

**3.12. Chuyển đổi kiểu dữ liệu**

In [19]:
import tensorflow as tf
import numpy as np

t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
print("\n")

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)
print("\n")


tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>


tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>




**3.13. Các phép toán trong tensorflow**

In [23]:
import tensorflow as tf
import numpy as np

x = tf.constant(2, dtype=tf.float32)
print("Căn bậc 2 của 2:", tf.sqrt(x), end="\n\n")

a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
print("Cộng dùng tf.add:", tf.add(a, b), end="\n\n")
print("Cộng dùng toán tử +:", a + b, end="\n\n")

a_mul = tf.constant([[1, 2]], tf.int32)
b_mul = tf.constant([[3, 4]], tf.int32)
print("Nhân dùng tf.multiply:", tf.multiply(a_mul, b_mul), end="\n\n")
print("Nhân dùng toán tử *:", a_mul * b_mul, end="\n\n")

# Các phép toán mở rộng trên Vector
v1 = tf.constant([6., 6., 6.])
v2 = tf.constant([4., 4., 4.])
v3 = tf.constant([3., 3., 3.])

print("tf.scalar_mul(3, v1):", tf.scalar_mul(3, v1), end="\n\n")
print("tf.negative(v1):", tf.negative(v1), end="\n\n")
print("tf.add_n([v1, v2, v3]):", tf.add_n([v1, v2, v3]), end="\n\n")

Căn bậc 2 của 2: tf.Tensor(1.4142135, shape=(), dtype=float32)

Cộng dùng tf.add: tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)

Cộng dùng toán tử +: tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)

Nhân dùng tf.multiply: tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)

Nhân dùng toán tử *: tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)

tf.scalar_mul(3, v1): tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)

tf.negative(v1): tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)

tf.add_n([v1, v2, v3]): tf.Tensor([13. 13. 13.], shape=(3,), dtype=float32)



**3.14. Các phép toán làm tròn và so sánh**