<a href="https://colab.research.google.com/github/nguyentrongnguyen3004-eng/Th_Deep_Learning/blob/main/th_deeplearning_b2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**3.1. Tensor 0-chiều**

In [1]:
import tensorflow as tf
import numpy as np

# Tạo tensor 0-chiều (Scalar) mặc định là int32
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.2. Tensor 1-chiều**

In [2]:
import tensorflow as tf
import numpy as np

# Tạo tensor 1-chiều
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.3. Tensor 2-chiều (ma trận)**


In [3]:
import tensorflow as tf
import numpy as np

# Tạo tensor 2-chiều
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.4. Tensor n-chiều (nhiều trục)**

In [4]:
import tensorflow as tf
import numpy as np

# Tạo tensor n-chiều
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)

# Tạo các tensor scalar với kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


**3.5. Thuộc tính của tensor**

In [5]:
import tensorflow as tf
import numpy as np

# Tạo tensor n-chiều
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],
])
print(rank_3_tensor)

print('shape:', rank_3_tensor.shape)
print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


**3.6. Tạo tensor tự động gán giá trị 0 ban đầu**

In [6]:
import tensorflow as tf
import numpy as np

t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


**3.7. Tạo tensor tự động gán giá trị 1 ban đầu**

In [7]:
import tensorflow as tf
import numpy as np

t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


**3.8. Tạo tensor tự động với giá trị bất kỳ**

In [9]:
import tensorflow as tf
import numpy as np

t_1 = tf.fill(3, 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


**3.9. Tạo tensor 1-chiều với hàm linspace**

In [10]:
import tensorflow as tf
import numpy as np

lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


**3.10. Tạo tensor 1-chiều với hàm range**

In [12]:
import tensorflow as tf
import numpy as np

range_tensor1 = tf.range(3.0, 7.0, delta = 0.5)
print(range_tensor1)

range_tensor2 = tf.range(3.0, delta = 0.5)
print(range_tensor2)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


**3.11. Tạo tensor với giá trị ngẫu nhiên**

In [17]:
import tensorflow as tf
import numpy as np

# Hàm random.normal
range_tensor_n1 = tf.random.normal([5])
print(range_tensor_n1)
print("\n")
range_tensor_n2 = tf.random.normal([3, 3])
print(range_tensor_n2)
print("\n")

# Hàm random.truncated_normal
range_tensor_t1 = tf.random.truncated_normal([5])
print(range_tensor_t1)
print("\n")
range_tensor_t2 = tf.random.truncated_normal([3, 2])
print(range_tensor_t2)
print("\n")
range_tensor_t3 = tf.random.truncated_normal([3, 2, 2])
print(range_tensor_t3)
print("\n")

# Hàm random.uniform
range_tensor_u1 = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor_u1)
print("\n")
range_tensor_u2 = tf.random.uniform([3, 2], minval=10, maxval=20)
print(range_tensor_u2)
print("\n")
range_tensor_u3 = tf.random.uniform([3, 2, 5], minval=10, maxval=20)
print(range_tensor_u3)
print("\n")

# Ngẫu nhiên kết hợp Shuffle xáo trộn
range_tensor_shuffle = tf.random.uniform([5], minval=10, maxval=20)
print("Gốc trước khi shuffle:", range_tensor_shuffle)
print("Sau khi shuffle:", tf.random.shuffle(range_tensor_shuffle))

tf.Tensor([ 0.34687647  1.1261046  -0.15452613 -0.623581    0.26764584], shape=(5,), dtype=float32)


tf.Tensor(
[[-1.0252979  -1.2696898   0.01547301]
 [ 1.8827355   0.6295514   0.95098686]
 [-0.6562238   0.94028145  0.7048137 ]], shape=(3, 3), dtype=float32)


tf.Tensor([-0.19683534  0.5275591  -1.214848    0.5976333  -0.7578208 ], shape=(5,), dtype=float32)


tf.Tensor(
[[-0.1258505  -1.0937433 ]
 [-0.41855773  1.1980511 ]
 [-0.15754181 -1.2092648 ]], shape=(3, 2), dtype=float32)


tf.Tensor(
[[[ 0.97375923 -0.6856656 ]
  [ 1.9765818  -0.28502798]]

 [[ 0.01415333  0.4162242 ]
  [-1.928093    1.5524323 ]]

 [[ 0.49493587 -0.23310217]
  [-0.00234946 -1.1202714 ]]], shape=(3, 2, 2), dtype=float32)


tf.Tensor([12.953327 12.057134 17.861912 10.088321 12.354398], shape=(5,), dtype=float32)


tf.Tensor(
[[18.833809 11.744705]
 [16.847942 15.683435]
 [15.991978 18.158646]], shape=(3, 2), dtype=float32)


tf.Tensor(
[[[12.716797 10.677578 18.15875  16.701283 18.921906]
  [12.383936 14.3406

**3.12. Chuyển đổi kiểu dữ liệu**

In [19]:
import tensorflow as tf
import numpy as np

t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
print("\n")

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, '---', t_int.dtype)
print("\n")


tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>


tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>




**3.13. Các phép toán trong tensorflow**

In [23]:
import tensorflow as tf
import numpy as np

x = tf.constant(2, dtype=tf.float32)
print("Căn bậc 2 của 2:", tf.sqrt(x), end="\n\n")

a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
print("Cộng dùng tf.add:", tf.add(a, b), end="\n\n")
print("Cộng dùng toán tử +:", a + b, end="\n\n")

a_mul = tf.constant([[1, 2]], tf.int32)
b_mul = tf.constant([[3, 4]], tf.int32)
print("Nhân dùng tf.multiply:", tf.multiply(a_mul, b_mul), end="\n\n")
print("Nhân dùng toán tử *:", a_mul * b_mul, end="\n\n")

# Các phép toán mở rộng trên Vector
v1 = tf.constant([6., 6., 6.])
v2 = tf.constant([4., 4., 4.])
v3 = tf.constant([3., 3., 3.])

print("tf.scalar_mul(3, v1):", tf.scalar_mul(3, v1), end="\n\n")
print("tf.negative(v1):", tf.negative(v1), end="\n\n")
print("tf.add_n([v1, v2, v3]):", tf.add_n([v1, v2, v3]), end="\n\n")

Căn bậc 2 của 2: tf.Tensor(1.4142135, shape=(), dtype=float32)

Cộng dùng tf.add: tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)

Cộng dùng toán tử +: tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)

Nhân dùng tf.multiply: tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)

Nhân dùng toán tử *: tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)

tf.scalar_mul(3, v1): tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)

tf.negative(v1): tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)

tf.add_n([v1, v2, v3]): tf.Tensor([13. 13. 13.], shape=(3,), dtype=float32)



**3.14. Các phép toán làm tròn và so sánh**

In [24]:
import tensorflow as tf
import numpy as np

t = tf.constant([-6.5, -3.5, 3.5, 6.5])
print("Gốc:", t)
print("tf.round:", tf.round(t))
print("tf.math.rint:", tf.math.rint(t))
print("tf.math.ceil:", tf.math.ceil(t))
print("tf.math.floor:", tf.math.floor(t))

Gốc: tf.Tensor([-6.5 -3.5  3.5  6.5], shape=(4,), dtype=float32)
tf.round: tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.math.rint: tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.math.ceil: tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
tf.math.floor: tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


**3.15. Các phép toán trên vector và ma trận**

In [25]:
import tensorflow as tf
import numpy as np

t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t4 = tf.constant([[7., 8.], [9., 10.], [11., 12.]])

print("Tensordot axes=0:\n", tf.tensordot(t1, t2, 0))
print("Tensordot axes=1:", tf.tensordot(t1, t2, 1))
print("Cross product (Tích có hướng):", tf.linalg.cross(t1, t2))
print("Matmul (Nhân ma trận):\n", tf.matmul(t3, t4))
print("Trích xuất / Tạo ma trận đường chéo:\n", tf.linalg.diag(t3))
print("Trace (Vết ma trận):", tf.linalg.trace(t3))
print("Transpose (Chuyển vị):\n", tf.transpose(t3))
print("Identity Matrix (Ma trận đơn vị):\n", tf.eye(5, 5))

Tensordot axes=0:
 tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
Tensordot axes=1: tf.Tensor(20.0, shape=(), dtype=float32)
Cross product (Tích có hướng): tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
Matmul (Nhân ma trận):
 tf.Tensor(
[[ 58.  64.]
 [139. 154.]], shape=(2, 2), dtype=float32)
Trích xuất / Tạo ma trận đường chéo:
 tf.Tensor(
[[[1. 0. 0.]
  [0. 2. 0.]
  [0. 0. 3.]]

 [[4. 0. 0.]
  [0. 5. 0.]
  [0. 0. 6.]]], shape=(2, 3, 3), dtype=float32)
Trace (Vết ma trận): tf.Tensor(6.0, shape=(), dtype=float32)
Transpose (Chuyển vị):
 tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
Identity Matrix (Ma trận đơn vị):
 tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


**3.16. Biến trong tensorflow**

In [26]:
import tensorflow as tf
import numpy as np

toan = tf.Variable(8.5, dtype=tf.float32)
diem = tf.Variable([5, 9])
print("Biến ban đầu:", diem.numpy())

diem.assign([8, 10])
print("Sau khi assign:", diem.numpy())

diem.assign_add([1, 1])
print("Sau khi assign_add:", diem.numpy())

diem.assign_sub([5, 5])
print("Sau khi assign_sub:", diem.numpy())

Biến ban đầu: [5 9]
Sau khi assign: [ 8 10]
Sau khi assign_add: [ 9 11]
Sau khi assign_sub: [4 6]


**3.17. Môi trường tính toán Graph trong tensorflow**

In [28]:
import tensorflow as tf
import numpy as np

def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

a_function_that_uses_a_graph = tf.function(a_regular_function)

x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


In [29]:
import tensorflow as tf
import numpy as np

def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

@tf.function
def outer_function(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return a_regular_function(x, y, b)

rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()

print(rs)

[[12.]]


**3.18. Modules, Layers và Models**

In [30]:
import tensorflow as tf
import numpy as np

class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

# Khởi tạo mô hình đơn giản
simple_module = SimpleModule(name="simple")

# Thực thi và in các kết quả kiểm tra
rs = simple_module(tf.constant(5.0))
print(rs)
print("Train variables:", simple_module.trainable_variables)
print("All variables:", simple_module.variables)

class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

# You have made a model!
my_model = SequentialModule(name="the_model")

# Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)
Model results: tf.Tensor([[0.013914  3.9510036]], shape=(1, 2), dtype=float32)


**3.19. Lưu weight**

In [31]:
import tensorflow as tf
import numpy as np

chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0.013914  3.9510036]], shape=(1, 2), dtype=float32)


**BÀI TẬP 1**

In [53]:
import tensorflow as tf
import numpy as np

ex1 = tf.zeros([2, 3])
print(ex1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


**BÀI TẬP 2**

In [54]:
import tensorflow as tf
import numpy as np

X_ref = tf.constant([[1, 2, 3], [4, 5, 6]])
ex2 = tf.zeros_like(X_ref)
print(ex2)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


**BÀI TẬP 3**

In [55]:
import tensorflow as tf
import numpy as np

ex3 = tf.fill([3, 2], 5)
print(ex3)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


**BÀI TẬP 4**

In [56]:
import tensorflow as tf
import numpy as np

ex4_linspace = tf.linspace(5.0, 10.0, 50)
print("Sử dụng cách chia đều linspace:\n", ex4_linspace)

Sử dụng cách chia đều linspace:
 tf.Tensor(
[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ], shape=(50,), dtype=float32)


**BÀI TẬP 5**

In [57]:
import tensorflow as tf
import numpy as np

ex5 = tf.range(10, 101, delta=2)
print(ex5)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


**BÀI TẬP 6**

In [58]:
import tensorflow as tf
import numpy as np

ex6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print(ex6)

tf.Tensor(
[[ 3.4203398  0.9538676]
 [-1.3471526 -2.7335534]
 [ 2.1857245 -0.1522998]], shape=(3, 2), dtype=float32)


**BÀI TẬP 7**

In [59]:
import tensorflow as tf
import numpy as np

ex7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print(ex7)

tf.Tensor(
[[1.4442286  0.09412885]
 [0.7232208  1.4469049 ]
 [0.46660185 1.5123179 ]], shape=(3, 2), dtype=float32)


**BÀI TẬP 8**

In [60]:
import tensorflow as tf
import numpy as np

X_shuffle = tf.constant([[1, 2], [3, 4], [5, 6]])
ex8 = tf.random.shuffle(X_shuffle)
print(ex8)

tf.Tensor(
[[3 4]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)


**BÀI TẬP 9**

In [61]:
import tensorflow as tf
import numpy as np

large_tensor = tf.random.normal([10, 10, 3])
ex9 = tf.image.random_crop(large_tensor, size=[5, 5, 3])
print("Kích thước sau cắt:", ex9.shape)

Kích thước sau cắt: (5, 5, 3)


**BÀI TẬP 10**

In [62]:
import tensorflow as tf
import numpy as np

x_b10 = tf.random.normal([5])
y_b10 = tf.random.normal([5])
ex10 = tf.where(x_b10 < y_b10, x_b10 + y_b10, x_b10 - y_b10)
print(ex10)

tf.Tensor([ 0.66624427 -1.1679001   0.0560747   0.50268376 -0.87525976], shape=(5,), dtype=float32)


**BÀI TẬP 11**

In [63]:
import tensorflow as tf
import numpy as np

x_b11 = tf.random.uniform([3, 2], minval=5, maxval=10)
y_b11 = tf.random.uniform([2, 3], minval=15, maxval=20)
diag_x = tf.linalg.diag_part(x_b11)
ex11 = tf.matmul(x_b11, y_b11)
print("Kết quả nhân ma trận:\n", ex11)

Kết quả nhân ma trận:
 tf.Tensor(
[[311.81183 320.57855 291.69742]
 [271.87775 274.9239  245.60214]
 [325.625   335.7913  306.5411 ]], shape=(3, 3), dtype=float32)


**BÀI TẬP 12**

In [75]:
import tensorflow as tf

def tao_tensor_ngau_nhien():
    x = tf.random.normal([3, 2, 2])
    y = tf.random.normal([3, 2, 2])
    return x, y

@tf.function
def tinh_toan_tren_graph(tensor_x, tensor_y):

    phep_cong = tf.add(tensor_x, tensor_y)
    phep_tru = tf.subtract(tensor_x, tensor_y)
    phep_nhan = tf.multiply(tensor_x, tensor_y)
    phep_chia = tf.divide(tensor_x, tensor_y)

    return phep_cong, phep_tru, phep_nhan, phep_chia

X, Y = tao_tensor_ngau_nhien()

ket_qua_cong, ket_qua_tru, ket_qua_nhan, ket_qua_chia = tinh_toan_tren_graph(X, Y)

print("=== TENSOR X ===")
print(X.numpy())

print("\n=== TENSOR Y ===")
print(Y.numpy())

print("\n=== KẾT QUẢ PHÉP CỘNG (GRAPH) ===")
print(ket_qua_cong.numpy())

print("\n=== KẾT QUẢ PHÉP TRỪ (GRAPH) ===")
print(ket_qua_tru.numpy())

print("\n=== KẾT QUẢ PHÉP NHÂN (GRAPH) ===")
print(ket_qua_nhan.numpy())

print("\n=== KẾT QUẢ PHÉP CHIA (GRAPH) ===")
print(ket_qua_chia.numpy())

=== TENSOR X ===
[[[ 0.39676106 -0.3804517 ]
  [ 1.6083899  -1.2925313 ]]

 [[-0.1198419   0.64856523]
  [-1.2353482   0.4879859 ]]

 [[ 1.9789531  -0.94594884]
  [-0.32024616  0.5432777 ]]]

=== TENSOR Y ===
[[[-0.35996068 -1.2757922 ]
  [ 0.9308943   0.8384285 ]]

 [[-0.23947209 -1.1532557 ]
  [-0.14225727  0.5494351 ]]

 [[ 1.0132273   0.8317959 ]
  [ 0.45500776  0.04300296]]]

=== KẾT QUẢ PHÉP CỘNG (GRAPH) ===
[[[ 0.03680038 -1.6562439 ]
  [ 2.5392842  -0.45410275]]

 [[-0.359314   -0.50469047]
  [-1.3776054   1.037421  ]]

 [[ 2.9921803  -0.11415297]
  [ 0.1347616   0.58628064]]]

=== KẾT QUẢ PHÉP TRỪ (GRAPH) ===
[[[ 0.75672174  0.89534056]
  [ 0.67749554 -2.1309597 ]]

 [[ 0.1196302   1.801821  ]
  [-1.093091   -0.06144917]]

 [[ 0.9657258  -1.7777448 ]
  [-0.7752539   0.5002747 ]]]

=== KẾT QUẢ PHÉP NHÂN (GRAPH) ===
[[[-0.14281838  0.48537734]
  [ 1.497241   -1.083695  ]]

 [[ 0.02869879 -0.7479616 ]
  [ 0.17573728  0.26811656]]

 [[ 2.0051293  -0.7868363 ]
  [-0.14571449  0.023

**BÀI TẬP 13**

In [65]:
import tensorflow as tf
import numpy as np

class ModelEx13(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return tf.add(x, y)

model13 = ModelEx13()
print(model13(tf.constant(10), tf.constant(15)))

tf.Tensor(25, shape=(), dtype=int32)


**BÀI TẬP 14**

In [66]:
import tensorflow as tf
import numpy as np

class ModelEx14(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return tf.subtract(x, y), tf.multiply(x, y)

model14 = ModelEx14()
res_s, res_m = model14(tf.constant(20), tf.constant(4))
print(f"Hiệu = {res_s}, Tích = {res_m}")

Hiệu = 16, Tích = 80


**BÀI TẬP 15**

In [67]:
import tensorflow as tf
import numpy as np

class RectanglePerimeter(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return tf.multiply(tf.add(a, b), 2)

model15 = RectanglePerimeter()
print("Chu vi hình chữ nhật:", model15(tf.constant(5.0), tf.constant(8.0)))

Chu vi hình chữ nhật: tf.Tensor(26.0, shape=(), dtype=float32)


**BÀI TẬP 16**

In [68]:
import tensorflow as tf
import numpy as np

class BoxArea(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        s_xq = tf.multiply(tf.multiply(tf.add(a, b), c), 2)
        s_tp = tf.add(tf.multiply(tf.multiply(a, b), 2), s_xq)
        return s_xq, s_tp

model16 = BoxArea()
s_xung_quanh, s_toan_phan = model16(tf.constant(2.0), tf.constant(3.0), tf.constant(4.0))
print(f"Diện tích xung quanh = {s_xung_quanh}, Diện tích toàn phần = {s_toan_phan}")

Diện tích xung quanh = 40.0, Diện tích toàn phần = 52.0


**BÀI TẬP 17**

In [69]:
import tensorflow as tf
import numpy as np

class TrapezoidProofSides(tf.Module):
    @tf.function
    def __call__(self, AD, BC, AB, CD):
        cond1 = tf.reduce_all(tf.equal(AD, BC))
        cond2 = tf.reduce_all(tf.equal(AB, CD))
        return tf.logical_and(cond1, cond2)

model17 = TrapezoidProofSides()
print("Kết quả chứng minh:", model17(tf.constant(5), tf.constant(5), tf.constant(4), tf.constant(4)))

Kết quả chứng minh: tf.Tensor(True, shape=(), dtype=bool)


**BÀI TẬP 18**

In [70]:
import tensorflow as tf
import numpy as np

class TrapezoidProofBases(tf.Module):
    @tf.function
    def __call__(self, AD, BC, is_parallel_AD_BC):
        cond1 = tf.reduce_all(tf.equal(AD, BC))
        return tf.logical_and(cond1, is_parallel_AD_BC)

model18 = TrapezoidProofBases()
print("Kết quả chứng minh:", model18(tf.constant(6), tf.constant(6), tf.constant(True)))

Kết quả chứng minh: tf.Tensor(True, shape=(), dtype=bool)


**"BÀI TẬP 19**

In [71]:
import tensorflow as tf
import numpy as np

class TriangleMidline(tf.Module):
    @tf.function
    def __call__(self, AM, MB, is_parallel_MN_BC):

        is_M_midpoint = tf.reduce_all(tf.equal(AM, MB))
        is_N_midpoint = tf.logical_and(is_M_midpoint, is_parallel_MN_BC)
        return is_N_midpoint

model19 = TriangleMidline()
print("Chứng minh NA = NC thành công:", model19(tf.constant(3.5), tf.constant(3.5), tf.constant(True)))

Chứng minh NA = NC thành công: tf.Tensor(True, shape=(), dtype=bool)
